#!/bin/bash
SCALA_LIBRARY=~/.sbt/boot/scala-2.9.1/lib/scala-library.jar
java -Djava.library.path=./target/so -cp ${SCALA_LIBRARY}:./target/scala-2.9.1/helloworldjni_2.9.1-0.0.1-SNAPSHOT.jar:. org.digimead.HelloWorldJNI
